### ISSUE TITLE
Angular js

### ISSUE THREAD

**Issue by okancelik34** [j3k0/cordova-non-renewing-subscription#10]
How can ı add this plugin with angular js ng click?

**Comment by j3k0** [comment]
Sorry I can help with Angular, did you find a solution?

**Comment by petarov** [comment]
I can't get this to work as well. I think (but I'm not sure) @okancelik34  means that nothing happens when `nonRenewing.openSubscriptionManager();` gets called. 

I'm still tracing the issue, my subscriptions are being loaded ok as I saw when I set `verbosity: store.DEBUG`.

EDIT: I'm using Ionic 1.x btw.

**Comment by petarov** [comment]
@okancelik34 Here's one possible example. Also check out the [dialog options](https://github.com/j3k0/cordova-non-renewing-subscription#dialog-options).

``` js
  $scope.doPurchase = function(event)  {
    event.preventDefault();
    nonRenewing.openSubscriptionManager();   
  };

  <button class="button button-block" ng-click="doPurchase($event)">Buy</button>
```
